import assert from 'node:assert/strict';
import fs from 'node:fs';

const source = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const projection = fs.readFileSync(new URL('../src/status-projection.js', import.meta.url), 'utf8');
assert.match(projection, /export function projectActiveStatus/);
assert.match(projection, /entries\.slice\(0, 2\)/);
assert.match(source, /import \{ projectActiveStatus \} from '\.\/src\/status-projection\.js'/);
assert.match(source, /const activeStatus = projectActiveStatus/);
assert.match(source, /projectActiveStatus\(\{ hingeElements: state\.hingeElements/);
assert.match(source, /function drawDestructibleContactShadow\(item\)/);
assert.match(source, /function drawDestructibleMaterialInset\(item, palette\)/);
assert.match(source, /function drawDestructibleDamageScars\(item, palette\)/);
assert.match(source, /Damage stages need a material-shaped read/);
assert.match(source, /drawDestructibleDamageScars\(item, palette\);/);
assert.match(source, /item\.kind === 'crate'/);
assert.match(source, /item\.kind === 'pipe'/);
assert.match(source, /item\.kind === 'drum'/);
assert.match(source, /drawDestructibleMaterialInset\(item, palette\);/);
assert.match(source, /item\.destroyed \? \.24 : \.34/);
assert.match(source, /item\.destroyed \? \.08 : \.14/);
assert.match(source, /drawDestructibleContactShadow\(item\);/);
assert.match(source, /Destroyed salvage remains a gameplay-readable object/);
assert.match(source, /ctx\.fillText\('SALVAGE', 0, item\.r \+ 15\)/);
assert.match(source, /ctx\.fillRect\(-20, item\.r \+ 8, 40, 11\)/);
assert.match(source, /ctx\.font = 'bold 7px Trebuchet MS'/);
assert.match(source, /function drawTargetContactShadow\(target\)/);
assert.match(source, /ctx\.globalAlpha = \.32/);
assert.match(source, /ctx\.ellipse\(3, radius \* \.72, radius \* 1\.08, radius \* \.3/);
assert.match(source, /drawTargetContactShadow\(target\);/);
assert.match(source, /function targetMaterialFamily\(target\)/);
assert.match(source, /function drawTargetMaterialCue\(target\)/);
assert.match(source, /target\.material === 'stone'/);
assert.match(source, /ctx\.strokeStyle = '#0d1211'/);
assert.match(source, /drawTargetMaterialCue\(target\);/);
assert.match(source, /target\.hitPulse = 8/);
assert.match(source, /target\.hitPulse = Math\.max\(0, target\.hitPulse - frameScale\)/);
assert.match(source, /function drawTargetImpactPulse\(target\)/);
assert.match(source, /drawTargetImpactPulse\(target\);/);
assert.match(source, /ctx\.arc\(0, 0, target\.r \+ 5 \+ \(1 - pulse\) \* 9/);
assert.doesNotMatch(source, /drawTargetMaterialCue\(target, index\)/);
assert.match(source, /function drawActiveElementChips\(\)/);
assert.match(source, /function drawHybridCue\(\)/);
assert.match(source, /'steam-fracture': \['STEAM'/);
assert.match(source, /const width = Math\.min\(92, W \* \.28\), x = \(W - width\) \/ 2, y = 78, height = 24/);
assert.match(source, /drawActiveElementChips\(\); drawHybridCue\(\); drawObjectiveCue\(\);/);
assert.match(source, /const y = 78; \/\/ keep active chips below the objective cue/);
assert.match(source, /function drawObjectiveCue\(\)/);
assert.match(source, /Keep the objective legible after the 360px canvas is scaled into a 320px phone/);
assert.match(source, /Math\.min\(104, Math\.max\(92, W \* \.28\)\)/);
assert.match(source, /y = 42, height = 34/);
assert.match(projection, /entries\.slice\(0, 2\)/);
assert.match(source, /drawActiveElementChips\(\);/);
assert.match(source, /family === 0/);
assert.match(source, /family === 1/);
assert.match(source, /ctx\.strokeRect\(-target\.r \* \.66/);
assert.match(source, /const integrityRatio = Math\.max\(0, Math\.min\(1, item\.integrity \/ item\.maxIntegrity\)\)/);
assert.match(source, /ctx\.fillRect\(-barWidth \/ 2, barY, barWidth \* integrityRatio, barHeight\)/);
assert.match(source, /const damagePulse = Math\.min\(1, item\.damageCooldown \/ 8\)/);
assert.match(source, /ctx\.beginPath\(\); ctx\.arc\(0, 0, item\.r \+ 4 \+ \(1 - damagePulse\) \* 4/);
assert.match(source, /function activateDamagePulseReviewFixture\(\)/);
assert.match(source, /get\('review'\) !== 'damage-pulse'/);
assert.match(source, /target\.integrity = target\.maxIntegrity \* \.56/);
assert.match(source, /target\.damageCooldown = 6/);
assert.match(source, /overlay\.hidden = true/);
assert.match(source, /dataset\.reviewFixture = 'damage-pulse'/);
assert.match(source, /function activateFlipperContactReviewFixture\(\)/);
assert.match(source, /const fixtureNormal = \{ x: Math\.sin\(flipper\.angle\), y: -Math\.cos\(flipper\.angle\) \}/);
assert.match(source, /flipper\.angularVelocity = -8/);
assert.match(source, /contactPoint\.x \+ fixtureNormal\.x \* 12/);
assert.match(source, /review=flipper-contact/);
assert.match(source, /for \(const side of \['left', 'right'\]\)/);
assert.match(source, /dataset\.reviewFlipperSamples/);
assert.match(source, /dataset\.reviewFlipperSides/);
assert.match(source, /activateFlipperContactReviewFixture\(\);/);
assert.match(source, /import \{ collectRuntimeContactCandidates, dispatchRuntimeContact, selectEarliestContact \} from '\.\/src\/contact-manifold\.js'/);
assert.match(source, /dispatchRuntimeContact\(runtimeContactWinner/);
assert.match(source, /collectRuntimeContactCandidates\(\{ circle: primaryCircleCandidate, segment: preStaticSegmentCandidate, flipper: preSelectedFlipperCandidate, boundaries: preBoundaryCandidates \}\)/);
assert.match(source, /collectBoundaryContactCandidates\(b, table\)/);
assert.match(source, /boundary: winner => \{ resolveBoundaryContact\(b, winner\.normal, winner\.point, winner\.penetration\); \}/);
assert.match(source, /circle: \(\) => \{/);
assert.match(source, /segment: \(\) => \{ segmentCollisionWithResidual\(b, preStaticSegmentCandidate\.segment, routeGravity, dt\)/);
assert.match(source, /flipper: \(\) => \{/);
assert.match(source, /state\.physicsTelemetry\.manifoldFamily = runtimeContactWinner\?\.kind \|\| null/);
assert.match(source, /selectEarliestFlipperContact/);
assert.doesNotMatch(source, /const flipperCandidates = \[\]/);
assert.doesNotMatch(source, /const selectedFlipperCandidate = selectEarliestFlipperContact\(flipperCandidates\)/);
assert.match(source, /resolveFlipperCollision\(b, flipper, side, side === 'left' \? input\.left : input\.right, contact\)/);
assert.match(source, /contact\.t < 1\) advancePrimaryBallResidual\(b, routeGravity, dt, contact\.t\)/);
assert.match(source, /drainRecoveryResidualDt\(dt, lateFlipperCandidate\)/);
assert.match(source, /const residualDt = drainRecoveryResidualDt\(dt, lateFlipperCandidate\)/);
assert.match(source, /b\.cradleSide === otherSide && hingeCradle\(otherSide\)/);
assert.match(source, /settled on the hinge; keep cradle maintenance alive/);
assert.match(source, /activateDamagePulseReviewFixture\(\);/);
assert.match(source, /function activateDestructionRunReviewFixture\(\)/);
assert.match(source, /get\('review'\) !== 'destruction-run'/);
assert.match(source, /applyDestructibleContact\(target, contact\)/);
assert.match(source, /dataset\.reviewContactCount/);
assert.match(source, /dataset\.reviewImpactSpeed/);
assert.match(source, /dataset\.reviewDamageStages/);
assert.match(source, /dataset\.reviewRewardTransitions/);
assert.match(source, /activateDestructionRunReviewFixture\(\);/);
assert.match(source, /import \{ runPhysicsCalibration \} from '\.\/src\/physics-calibration\.mjs'/);
assert.match(source, /function activateCalibrationReviewFixture\(\)/);
assert.match(source, /get\('review'\) !== 'calibration'/);
assert.match(source, /runPhysicsCalibration\(\)/);
assert.match(source, /dataset\.reviewCalibrationPass/);
assert.match(source, /dataset\.reviewCalibrationGates/);
assert.match(source, /activateCalibrationReviewFixture\(\);/);
assert.match(source, /function activateGrayscaleReviewFixture\(\)/);
assert.match(source, /get\('review'\) !== 'grayscale'/);
assert.match(source, /canvas\.classList\.add\('review-grayscale'\)/);
assert.match(source, /dataset\.reviewFixture = 'grayscale'/);
assert.match(source, /activateGrayscaleReviewFixture\(\);/);
assert.match(source, /function activateDepthReviewFixture\(\)/);
assert.match(source, /get\('review'\) !== 'depth'/);
assert.match(source, /Review fixture · frozen depth audit/);
assert.match(source, /dataset\.reviewFixture = 'depth'/);
assert.match(source, /activateDepthReviewFixture\(\);/);
assert.match(source, /function activateActiveElementsReviewFixture\(\)/);
assert.match(source, /get\('review'\) !== 'active-elements'/);
assert.match(source, /dataset\.reviewFixture = 'active-elements'/);
assert.match(source, /Fire: \{ stacks: 3, timer: 360 \}/);
assert.match(source, /Water: \{ stacks: 2, timer: 240 \}/);
assert.match(source, /activateActiveElementsReviewFixture\(\);/);
assert.match(source, /function drawFlipperContactShadow\(end, width\)/);
assert.match(source, /const collarRadius = item\.r \+ 5/);
assert.match(source, /ctx\.createRadialGradient\(item\.x - item\.r \* \.28/);
assert.match(source, /Nested shell, recessed face, and a single warm key catch/);
assert.match(source, /ctx\.arc\(item\.x - item\.r \* \.08, item\.y - item\.r \* \.08, item\.r \* \.72/);
assert.match(source, /ctx\.globalAlpha = \.34/);
assert.match(source, /drawFlipperContactShadow\(end, width\);/);
assert.match(source, /const deckInsetOpacity = \.78/);
assert.match(source, /function drawRecessedWellPlane\(\)/);
assert.match(source, /drawRecessedWellPlane\(\);/);
assert.match(source, /ctx\.fillStyle = wellGradient;/);
assert.match(source, /ctx\.globalAlpha = \.42/);
assert.match(source, /ctx\.globalAlpha = deckInsetOpacity; ctx\.drawImage\(spriteImages\.deckInset/);
assert.match(source, /function drawForegroundMechanismPlane\(\)/);
assert.match(source, /function drawMineDrain\(\)/);
assert.match(source, /drawMineDrain\(\); drawForegroundMechanismPlane\(\); drawWellFrontLip\(\);/);
assert.match(source, /function drawWellFrontLip\(\)/);
assert.match(source, /creates a readable occlusion break before the drain and flipper plane/);
assert.match(source, /drawForegroundMechanismPlane\(\); drawWellFrontLip\(\); drawFlippers\(\);/);
assert.match(source, /const top = H - 154, bottom = H - 106/);
assert.match(source, /ledge\.addColorStop\(\.18, '#526e63'\)/);
assert.match(source, /function drawWellWallBevel\(\)/);
assert.match(source, /const bevelTop = 124, bevelBottom = H - 112/);
assert.match(source, /ctx\.globalAlpha = \.36/);
assert.match(source, /drawWellWallBevel\(\);/);
assert.match(source, /function drawBumpers\(\)/);
assert.match(source, /const pulse = item\.type === 'pulse'; const armor = item\.type === 'armor'/);
assert.match(source, /Armor bumpers read as plated cages/);
assert.match(source, /for \(let plate = 0; plate < 8; plate \+= 1\)/);
assert.match(source, /Pulse bumpers expose a mechanical coil/);
assert.match(source, /for \(let coil = 0; coil < 4; coil \+= 1\)/);
assert.match(source, /ctx\.strokeRect\(item\.x - item\.r \* \.32, item\.y - 2/);
assert.match(source, /ctx\.moveTo\(item\.x - item\.r \* \.74, item\.y - item\.r \* \.42\)/);
assert.match(source, /function drawMineGrime\(\)/);
assert.match(source, /const grimeMarks = \[\[34, 156, 18, 5\]/);
assert.match(source, /drawMineGrime\(\);/);
assert.match(source, /function drawMineStructures\(\)/);
assert.match(source, /const face = ctx\.createLinearGradient\(-width \/ 2, 0, width \/ 2, 0\)/);
assert.match(source, /const rockFace = \(x, y, scale, flip = 1\)/);
assert.match(source, /Irregular rock faces establish a third material family/);
assert.match(source, /rockFace\(82, 112, 1\); rockFace\(W - 82, 112, 1, -1\)/);
assert.match(source, /drawMineStructures\(\);/);
assert.match(source, /function drawMeters\(\)/);
assert.match(source, /drawMeter\(30, 138, 'FUEL'/);
assert.match(source, /drawMeter\(216, 114, 'TARGET'/);
assert.match(source, /drawMineStructures\(\); drawMeters\(\);/);
const liveDraw = source.match(/function draw\(\) \{([\s\S]*?)\n  \}/)?.[1] || '';
assert.ok(liveDraw.indexOf('drawRecessedWellPlane();') < liveDraw.indexOf('drawDeckDetails();'), 'recessed well must sit behind authored deck details');
assert.ok(liveDraw.indexOf('drawDeckDetails();') < liveDraw.indexOf('drawTargets();'), 'deck planes must be composed before gameplay objects');
assert.match(source, /class="upgrade-effect"/);
assert.match(source, /overlayCopy\.className = 'upgrade-context'/);
assert.match(source, /upgrade\.text/);
assert.match(source, /HINGE LOADOUT/);
assert.match(source, /consumeRootSling/);
assert.match(source, /applyImpulse\(ball\.physics, sling\.impulse\)/);
assert.match(source, /observeStructureContact\(item\.id, \{ x: item\.x, y: item\.y \}, contact\.normal, item\.material\)/);
assert.match(source, /consumeSlurryBind/);
assert.match(source, /slurry-bind-contact/);
assert.match(source, /Redirected along the anchor/);
assert.match(source, /resolveFireTrailDamage/);
assert.match(source, /event\.type === 'fire-trail-tick' && event\.damageEnabled/);
assert.match(source, /burned through by ember trail/);

assert.match(source, /syncPixelsFromPhysics\(ball\); ball\.lastContact = contact;.*capBallSpeed\(ball\); state\.lastFlipperContact = summarizeFlipperContact/s,
  'flipper telemetry must summarize the capped live velocity');
assert.match(source, /summarizeFlipperContactSources/);
assert.match(source, /physicsTelemetry: \{ physicsStepMs: 0, contactCount: 0, substepCount: 0, speedCapCount: 0, activeBodyCount: 1, manifoldFamily: null, manifoldT: null, manifoldCandidateCount: 0 \}/);
assert.match(source, /state\.physicsTelemetry\.manifoldCandidateCount = runtimeContactCandidates\.length/);
assert.match(source, /Manifold: \$\{telemetry\.manifoldFamily \|\| 'none'\} \/ \$\{telemetry\.manifoldCandidateCount\}/);
assert.match(source, /if \(speed > maxSpeed && state\?\.physicsTelemetry\) state\.physicsTelemetry\.speedCapCount \+= 1/);
assert.match(source, /Caps: \$\{telemetry\.speedCapCount\}/);
assert.match(source, /performance\.now\(\)/);
assert.match(source, /state\.physicsTelemetry\.contactCount \+= 1/);
assert.match(source, /function circleCollision\(ball, item\)/);
assert.match(source, /sweptCircleContact\(\{ x: ball\.prevX, y: ball\.prevY \}, \{ x: ball\.x, y: ball\.y \}, \{ x: item\.x, y: item\.y \}, min\)/);
assert.match(source, /contact\.sweptT = swept\?\.t \?\? 1/);
assert.match(source, /Step: \$\{telemetry\.physicsStepMs\.toFixed\(2\)\}ms/);
assert.match(source, /swept = sweptSegmentContact\(ball, segment, radius\)/);
assert.match(source, /contact\.sweptT = swept\?\.t \?\? 1/);
assert.match(source, /function segmentCollisionWithResidual\(ball, segment, gravityMps2, dt\)/);
assert.match(source, /function advancePrimaryBallResidual\(ball, gravityMps2, dt, contactFraction\) \{[\s\S]*?ball\.prevX = ball\.x; ball\.prevY = ball\.y;[\s\S]*?integratePrimaryBall\(ball, gravityMps2, residualDt\)/);
assert.match(source, /const preStaticSegmentCandidates = collectStaticSegmentCandidates\(b\)/);
assert.match(source, /const preStaticSegmentCandidate = selectEarliestSweptContact\(preStaticSegmentCandidates\)/);
assert.match(source, /The pre-resolution candidate is authoritative/);
assert.match(source, /segment: \(\) => \{ segmentCollisionWithResidual\(b, preStaticSegmentCandidate\.segment, routeGravity, dt\); return \{ contactFraction: preStaticSegmentCandidate\.swept\.t \}; \}/);
assert.doesNotMatch(source, /const staticSegmentCandidates = \[\]/);
assert.doesNotMatch(source, /const staticSegmentCandidate = selectEarliestSweptContact\(staticSegmentCandidates\)/);
assert.match(source, /function segmentCollisionWithResidual[\s\S]*?advancePrimaryBallResidual\(ball, gravityMps2, dt, contact\.sweptT\)/);
assert.match(source, /function destructibleCollision\(ball, item\)/);
assert.match(source, /sweptCircleContact\(\{ x: ball\.prevX, y: ball\.prevY \}/);
assert.match(source, /advancePrimaryBallResidual\(b, routeGravity, dt, contact\.sweptT\)/);
assert.match(source, /const primaryCircleCandidates = \[\]/);
assert.match(source, /selectEarliestSweptContact\(primaryCircleCandidates\)/);
assert.match(source, /const \{ type, item \} = primaryCircleCandidate/);
assert.match(source, /destructibleCollision\(b, item\)/);
assert.match(source, /contactX = swept\.x; contactY = swept\.y/);
assert.match(source, /if \(contact && !contact\.separating\) \{[\s\S]*?if \(contact\.sweptT < 1\) advancePrimaryBallResidual\(b, routeGravity, dt, contact\.sweptT\);/);
console.log('renderer-contract: target material cues, review fixtures, and physics telemetry present');