import assert from 'node:assert/strict';
import fs from 'node:fs';

const source = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const projection = fs.readFileSync(new URL('../src/status-projection.js', import.meta.url), 'utf8');
assert.match(projection, /export function projectActiveStatus/);
assert.match(projection, /entries\.slice\(0, 2\)/);
assert.match(source, /import \{ projectActiveStatus \} from '\.\/src\/status-projection\.js'/);
assert.match(source, /const activeStatus = projectActiveStatus/);
assert.match(source, /projectActiveStatus\(\{ hingeElements: state\.hingeElements/);
assert.match(source, /function drawDestructibleContactShadow\(item\)/);
assert.match(source, /item\.destroyed \? \.24 : \.34/);
assert.match(source, /item\.destroyed \? \.08 : \.14/);
assert.match(source, /drawDestructibleContactShadow\(item\);/);
assert.match(source, /Destroyed salvage remains a gameplay-readable object/);
assert.match(source, /ctx\.fillText\('SALVAGE', 0, item\.r \+ 15\)/);
assert.match(source, /ctx\.fillRect\(-20, item\.r \+ 8, 40, 11\)/);
assert.match(source, /ctx\.font = 'bold 7px Trebuchet MS'/);
assert.match(source, /function drawTargetContactShadow\(target\)/);
assert.match(source, /ctx\.globalAlpha = \.32/);
assert.match(source, /ctx\.ellipse\(3, radius \* \.72, radius \* 1\.08, radius \* \.3/);
assert.match(source, /drawTargetContactShadow\(target\);/);
assert.match(source, /function drawTargetMaterialCue\(target, index\)/);
assert.match(source, /ctx\.strokeStyle = '#0d1211'/);
assert.match(source, /drawTargetMaterialCue\(target, index\);/);
assert.match(source, /function drawActiveElementChips\(\)/);
assert.match(source, /const y = 78; \/\/ keep active chips below the objective cue/);
assert.match(projection, /entries\.slice\(0, 2\)/);
assert.match(source, /drawActiveElementChips\(\);/);
assert.match(source, /family === 0/);
assert.match(source, /family === 1/);
assert.match(source, /ctx\.strokeRect\(-target\.r \* \.66/);
assert.match(source, /const integrityRatio = Math\.max\(0, Math\.min\(1, item\.integrity \/ item\.maxIntegrity\)\)/);
assert.match(source, /ctx\.fillRect\(-barWidth \/ 2, barY, barWidth \* integrityRatio, barHeight\)/);
assert.match(source, /const damagePulse = Math\.min\(1, item\.damageCooldown \/ 8\)/);
assert.match(source, /ctx\.beginPath\(\); ctx\.arc\(0, 0, item\.r \+ 4 \+ \(1 - damagePulse\) \* 4/);
assert.match(source, /function activateDamagePulseReviewFixture\(\)/);
assert.match(source, /get\('review'\) !== 'damage-pulse'/);
assert.match(source, /target\.integrity = target\.maxIntegrity \* \.56/);
assert.match(source, /target\.damageCooldown = 6/);
assert.match(source, /overlay\.hidden = true/);
assert.match(source, /dataset\.reviewFixture = 'damage-pulse'/);
assert.match(source, /function activateFlipperContactReviewFixture\(\)/);
assert.match(source, /const fixtureNormal = \{ x: Math\.sin\(flipper\.angle\), y: -Math\.cos\(flipper\.angle\) \}/);
assert.match(source, /flipper\.angularVelocity = -8/);
assert.match(source, /contactPoint\.x \+ fixtureNormal\.x \* 12/);
assert.match(source, /review=flipper-contact/);
assert.match(source, /for \(const side of \['left', 'right'\]\)/);
assert.match(source, /dataset\.reviewFlipperSamples/);
assert.match(source, /dataset\.reviewFlipperSides/);
assert.match(source, /activateFlipperContactReviewFixture\(\);/);
assert.match(source, /activateDamagePulseReviewFixture\(\);/);
assert.match(source, /function activateDestructionRunReviewFixture\(\)/);
assert.match(source, /get\('review'\) !== 'destruction-run'/);
assert.match(source, /applyDestructibleContact\(target, contact\)/);
assert.match(source, /dataset\.reviewContactCount/);
assert.match(source, /dataset\.reviewImpactSpeed/);
assert.match(source, /dataset\.reviewDamageStages/);
assert.match(source, /dataset\.reviewRewardTransitions/);
assert.match(source, /activateDestructionRunReviewFixture\(\);/);
assert.match(source, /function activateGrayscaleReviewFixture\(\)/);
assert.match(source, /get\('review'\) !== 'grayscale'/);
assert.match(source, /canvas\.classList\.add\('review-grayscale'\)/);
assert.match(source, /dataset\.reviewFixture = 'grayscale'/);
assert.match(source, /activateGrayscaleReviewFixture\(\);/);
assert.match(source, /function activateDepthReviewFixture\(\)/);
assert.match(source, /get\('review'\) !== 'depth'/);
assert.match(source, /Review fixture · frozen depth audit/);
assert.match(source, /dataset\.reviewFixture = 'depth'/);
assert.match(source, /activateDepthReviewFixture\(\);/);
assert.match(source, /function activateActiveElementsReviewFixture\(\)/);
assert.match(source, /get\('review'\) !== 'active-elements'/);
assert.match(source, /dataset\.reviewFixture = 'active-elements'/);
assert.match(source, /Fire: \{ stacks: 3, timer: 360 \}/);
assert.match(source, /Water: \{ stacks: 2, timer: 240 \}/);
assert.match(source, /activateActiveElementsReviewFixture\(\);/);
assert.match(source, /function drawFlipperContactShadow\(end, width\)/);
assert.match(source, /ctx\.globalAlpha = \.34/);
assert.match(source, /drawFlipperContactShadow\(end, width\);/);
assert.match(source, /const deckInsetOpacity = \.78/);
assert.match(source, /function drawRecessedWellPlane\(\)/);
assert.match(source, /drawRecessedWellPlane\(\);/);
assert.match(source, /ctx\.fillStyle = wellGradient;/);
assert.match(source, /ctx\.globalAlpha = \.42/);
assert.match(source, /ctx\.globalAlpha = deckInsetOpacity; ctx\.drawImage\(spriteImages\.deckInset/);
assert.match(source, /syncPixelsFromPhysics\(ball\); ball\.lastContact = contact;.*capBallSpeed\(ball\); state\.lastFlipperContact = summarizeFlipperContact/s,
  'flipper telemetry must summarize the capped live velocity');
assert.match(source, /summarizeFlipperContactSources/);
assert.match(source, /physicsTelemetry: \{ physicsStepMs: 0, contactCount: 0, substepCount: 0, activeBodyCount: 1 \}/);
assert.match(source, /performance\.now\(\)/);
assert.match(source, /state\.physicsTelemetry\.contactCount \+= 1/);
assert.match(source, /Step: \$\{telemetry\.physicsStepMs\.toFixed\(2\)\}ms/);
assert.match(source, /const swept = sweptSegmentContact\(ball, segment, radius\)/);
assert.match(source, /function destructibleCollision\(ball, item\)/);
assert.match(source, /sweptCircleContact\(\{ x: ball\.prevX, y: ball\.prevY \}/);
assert.match(source, /advancePrimaryBallResidual\(b, routeGravity, dt, contact\.sweptT\)/);
assert.match(source, /destructibleCollision\(b, item\)/);
assert.match(source, /contactX = swept\.x; contactY = swept\.y/);
console.log('renderer-contract: target material cues, review fixtures, and physics telemetry present');